const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('fs');
(async()=>{
 const browser=await chromium.launch({...(process.env.BROWSER_EXECUTABLE ? {executablePath:process.env.BROWSER_EXECUTABLE} : {}),headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}); const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const url=process.argv[2]||require('url').pathToFileURL(require('path').resolve(__dirname,'../dashboard/index.html')).href;
 await page.goto(url,{timeout:30000,waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.querySelector('#city-name')?.textContent.length>0,{timeout:30000});
 await page.screenshot({path:require('path').join(process.env.UI_TEST_OUTPUT || '/tmp','sber-site-desktop.png'),fullPage:true});
 const results=[]; const assert=(ok,label)=>{if(!ok)throw Error(label);results.push(label);};
 const check=async()=>{const state=await page.evaluate(async()=>{const d=await window.RESEARCH_DATA_READY;let city=Object.values(d.municipalities).find(c=>document.querySelector('#city-region').textContent.endsWith('ID '+c.id));let cat=document.querySelector('#category').value,h=document.querySelector('#horizon').value,m=document.querySelector('#month').value;let a=city.history[cat]?.[m],p=city.forecasts[cat]?.[h]?.[m];let e=a>0&&p?(a-p[0])/a*100:null;return{expected:e==null?'—':(e>0?'+':'')+e.toFixed(1)+'%',actual:document.querySelector('#city-error').textContent,month:m,cat,h,points:document.querySelectorAll('#map circle').length,table:document.querySelectorAll('#cities tr').length,chart:document.querySelectorAll('#forecast path').length};});assert(state.actual===state.expected,`Error matches saved data: ${state.cat}, h${state.h}, ${state.month}`);return state;};
 assert((await page.locator('#city-name').textContent()).includes('Орск'),'Initial real case: Orsk'); await check();
 for(const name of ['Уфа','Яльчикский','Орск']){await page.getByRole('button',{name,exact:true}).first().click();assert((await page.locator('#city-name').textContent()).includes(name),`Quick example ${name}`);await check();}
 const cats=await page.locator('#category option').evaluateAll(o=>o.map(x=>x.value));
 for(const cat of cats){await page.selectOption('#category',cat);for(const h of ['1','3','6','12']){await page.selectOption('#horizon',h);const months=await page.locator('#month option').evaluateAll(o=>o.map(x=>x.value));assert(months.length>0,`Months available: ${cat} h${h}`);for(const m of [...new Set([months[0],months[months.length-1]])]){await page.selectOption('#month',m);await check();}}}
 await page.selectOption('#category','Все категории');await page.selectOption('#horizon','1');await page.selectOption('#month','2024-05');
 await page.fill('#search','Уфа');assert((await page.locator('#city-name').textContent()).includes('Уфа'),'Search name selects city');
 await page.fill('#search','1673');assert((await page.locator('#city-name').textContent()).includes('Орск'),'Search ID selects city');
 await page.fill('#search','не существует xyz');assert(await page.locator('#cities tr').count()===0,'Empty search has no table results');assert((await page.locator('#no-map').textContent()).includes('По запросу не найдено'),'Empty search explains the retained detail');await page.fill('#search','');
 let point=page.locator('#map circle').first();const id=await point.getAttribute('data-id');await point.dispatchEvent('click');assert((await page.locator('#city-region').textContent()).endsWith('ID '+id),'Map selection updates detail');
 await page.locator('#cities button').first().click();await check();
 let queueChecks=[];for(const signal of ['peer','own']){await page.selectOption('#signal',signal);for(const m of await page.locator('#month option').evaluateAll(o=>o.map(x=>x.value))){await page.selectOption('#month',m);const count=await page.locator('.queue-item').count();const expected=await page.evaluate(async()=>{const d=await window.RESEARCH_DATA_READY;return Object.values(d.municipalities).filter(c=>c.alarms[document.querySelector('#signal').value]?.[document.querySelector('#month').value]?.episode).length;});assert(count===expected,`Queue matches saved episodes: ${signal} ${m}`);if(count){let text=await page.locator('.queue-item').first().evaluate(e=>e.firstChild.textContent);await page.locator('.queue-item').first().click();assert((await page.locator('#city-name').textContent())===text,'Queue click updates city');}queueChecks.push({signal,m,count});}}
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:require('path').join(process.env.UI_TEST_OUTPUT || '/tmp','sber-site-mobile.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile has no horizontal page overflow');
 for(const width of [768,1280,1440]){await page.setViewportSize({width,height:1000});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`No horizontal overflow at ${width}px`);}
 assert(errors.length===0,'No browser JavaScript errors');
 fs.writeFileSync(require('path').join(process.env.UI_TEST_OUTPUT || '/tmp','sber-site-test.json'),JSON.stringify({url,browser:browser.version(),testedAt:new Date().toISOString(),checks:results.length,results,queueChecks,errors},null,2));console.log(JSON.stringify({url,checks:results.length,errors,queueChecks}));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
